#include <syslog.h>

/* configuring syslog is optional, but if it is not configured 
it will use the deault options
identityString: const char* will be appended to all log messages */
void configure_syslog(const char* identityString){
	/* specify options for syslog 
	LOG_CONS: if there is an error sending to the system logger, then write the log
	message to the system console at /dev/console 
	LOG_PID: log the caller's PID to the log message as well */
	int logOptions = LOG_CONS | LOG_PID;

	int logFacility = LOG_USER; /* messages generated by random user processes */

	/* open a syslog with specified configuration */
	openlog(identityString, logOptions, logFacility);

	/* since openlog does not return a value (void) we do not have a way, of
	knowing that an error occured while configuring syslog */
}

/* Eduardo Rodriguez 2021 (c) (@erodrigufer). Licensed under GNU AGPLv3 */
