#include <syslog.h>

int configure_syslog(void){

	/* identityString: this const char* will be appended to all log messages */
	const char *identityString = "Server daemon";

	/* specify options for syslog 
	LOG_CONS: if there is an error sending to the system logger, then write the log
	message to the system console at /dev/console 
	LOG_PID: log the caller's PID to the log message as well */
	int logOptions = LOG_CONS | LOG_PID;

	int logFacility = LOG_USER; /* messages generated by random user processes */

	/* open a syslog with specified configuration */
	openlog(identityString, logOptions, logFacility);
	/* TODO: can openlog fail?? handle error */

	return 0;
}

