name: C Build (CI)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    # '**' stands for all possible characters, check
    # wildcards and patterns cheat sheet:
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

jobs:
  Server_Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: make server
      run: make server
    - name: test server availability
      run: ./serverAvailability
      working-directory: ./tests
    #- name: make distcheck
    #  run: make distcheck

  ncurses_Frontend:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-11, macos-10.15]
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: make client
      run: make client
