name: Unit-testing (CI)

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    # '**' stands for all possible characters, check
    # wildcards and patterns cheat sheet:
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: Run all unit tests
      run: make unit-test
